"""unary_functions"""

from typing import Any

from numpy.typing import NDArray

def sin(size: int, vec: NDArray[Any], result: NDArray[Any]) -> None: ...
def cos(size: int, vec: NDArray[Any], result: NDArray[Any]) -> None: ...
def tan(size: int, vec: NDArray[Any], result: NDArray[Any]) -> None: ...
def arcsin(size: int, vec: NDArray[Any], result: NDArray[Any]) -> None: ...
def arccos(size: int, vec: NDArray[Any], result: NDArray[Any]) -> None: ...
def arctan(size: int, vec: NDArray[Any], result: NDArray[Any]) -> None: ...
def exp(size: int, vec: NDArray[Any], result: NDArray[Any]) -> None: ...
def exp2(size: int, vec: NDArray[Any], result: NDArray[Any]) -> None: ...
def log(size: int, vec: NDArray[Any], result: NDArray[Any]) -> None: ...
def log2(size: int, vec: NDArray[Any], result: NDArray[Any]) -> None: ...
def sqrt(size: int, vec: NDArray[Any], result: NDArray[Any]) -> None: ...
def cbrt(size: int, vec: NDArray[Any], result: NDArray[Any]) -> None: ...
