### Taken from <https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions>

name: Documentation 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.11
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4.3.0
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      # The line below is to enable the docstring for the lbsim_interface.py
      - run: pip install --no-deps litebird_sim
      - run: pip install mkdocs-material mkdocstrings[python]
      - run: mkdocs gh-deploy --force
