### Running pytest

# setting up testing: <https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#testing-your-code>
# setting up compiler: <https://github.com/marketplace/actions/setup-c-c-compiler>

name: Tests
on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        mpi: ["mpich", "openmpi"]
        # Excluding the following because it is failing and remains stalled, without any useful error message
        exclude:
          - os: ubuntu-latest
            mpi: mpich
            python-version: "3.9"

    steps:
      - name: Checkout BrahMap repository
        uses: actions/checkout@v5.0.0
        with:
          submodules: true

      - name: Install MPI - ${{ matrix.mpi }}
        uses: mpi4py/setup-mpi@v1.3.5
        with:
          mpi: ${{ matrix.mpi }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install litebird_sim
        if: ${{ matrix.python-version == '3.12' }}
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/litebird/litebird_sim.git
          pip install deprecated

      - name: Install BrahMap
        run: |
          mpicxx --version
          python -m pip install --upgrade pip
          MPILD=mpicxx MPICC=mpicc MPICXX=mpicxx python3 -m pip install -v .

      - name: Test BrahMap with pytest
        if: ${{ matrix.python-version == '3.10' || matrix.python-version == '3.12' }}
        run: bash ${GITHUB_WORKSPACE}/tests/tools/mpiexec_test_loop.sh
